// This file autogenerated by generate-asset-types.js
// Do not modify it by hand. Any changes will be overwritten.
declare const snd_ballRollingRawAt3035: string;
export default snd_ballRollingRawAt3035;
